### PR TITLE
Create Clue

### PR DESCRIPTION
**Pull request by Killaforlifelol**
https://cdn.discordapp.com/attachments/822929347878715453/897951582069612564/steganography-2.png

I need help on to know what this picture means if you would please help me thanks.

### CODE REVIEW

**Comment by s373r** [comment]
hello @Killaforlifelol!

did you try to use steganography-png-decoder?

**Comment by Killaforlifelol** [comment]
> hello @Killaforlifelol!
> 
> did you try to use steganography-png-decoder?

Well yes I tried my hardest to figure out how to decode this image and I really need help to figuring out this code or meaning in the image.

**Comment by Killaforlifelol** [comment]
So Yea please may you help me try and figure out this code or meaning

**Comment by Killaforlifelol** [comment]
Hello I was wondering may you help me try and figure the code or meaning to this image?  Sent from Mail for Windows From: Dima PristupaSent: Saturday, October 30, 2021 10:01 AMTo: s373r/steganography-png-decoderCc: Killaforlifelol; MentionSubject: Re: [s373r/steganography-png-decoder] Create Clue (PR #7) hello @Killaforlifelol!did you try to use steganography-png-decoder?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by s373r** [comment]
@Killaforlifelol 

I assume it is a CTF task so could you share this task description? (It may contains tips)

**Comment by Killaforlifelol** [comment]
> @Killaforlifelol
> 
> I assume it is a CTF task so could you share this task description? (It may contain tips)

One sec I am trying to find some tip for the description.

**Comment by s373r** [comment]
@Killaforlifelol, any updates?

**Comment by Killaforlifelol** [comment]
> @Killaforlifelol, any updates?

Yes, almost

**Comment by Killaforlifelol** [comment]
Can you decode this image or 
image
?

**Comment by s373r** [comment]
hey @Killaforlifelol,

I'd like to remember to you this repository (and its issues section) is not related to solving CTF tasks itself. 

The repo (and main script) is useful for getting text chunks from PNG images. If a flag was hidden by another way so you need to find it.

If you really know that the flag in PNG text chunks and the script does not print it please create an issue for that (and attach a sample)

if not, then don't give up and keep looking, but use other tools.

**Comment by s373r** [comment]
Since this PR is not related to code I'll close it

Feel free to open an issue if needed

**Pull request closed without merging**
